services:
  postgresql:
    image: postgres:18
    container_name: postgresql
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    depends_on:
      - postgresql
    build: .
    container_name: app
    restart: always
    env_file: ./.env
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  db: